'use client'

import { motion } from 'framer-motion'
import { ComponentProps } from 'react'

// SSR-safe motion components that only render on client-side
export const ClientMotion = {
  div: motion.div,
  section: motion.section,
  article: motion.article,
  header: motion.header,
  footer: motion.footer,
  nav: motion.nav,
  main: motion.main,
  aside: motion.aside,
  button: motion.button,
  span: motion.span,
  p: motion.p,
  h1: motion.h1,
  h2: motion.h2,
  h3: motion.h3,
  h4: motion.h4,
  h5: motion.h5,
  h6: motion.h6,
  ul: motion.ul,
  ol: motion.ol,
  li: motion.li,
  a: motion.a,
  img: motion.img,
  form: motion.form,
  input: motion.input,
  textarea: motion.textarea,
  select: motion.select,
  option: motion.option,
  label: motion.label,
  fieldset: motion.fieldset,
  legend: motion.legend,
  table: motion.table,
  thead: motion.thead,
  tbody: motion.tbody,
  tr: motion.tr,
  th: motion.th,
  td: motion.td,
  canvas: motion.canvas,
  svg: motion.svg,
  path: motion.path,
  circle: motion.circle,
  rect: motion.rect,
  line: motion.line,
  polyline: motion.polyline,
  polygon: motion.polygon,
  ellipse: motion.ellipse,
  g: motion.g,
  defs: motion.defs,
  clipPath: motion.clipPath,
  mask: motion.mask,
  pattern: motion.pattern,
  image: motion.image,
  text: motion.text,
  tspan: motion.tspan,
  foreignObject: motion.foreignObject,
  use: motion.use,
  symbol: motion.symbol,
  marker: motion.marker,
  linearGradient: motion.linearGradient,
  radialGradient: motion.radialGradient,
  stop: motion.stop,
  filter: motion.filter,
  feGaussianBlur: motion.feGaussianBlur,
  feColorMatrix: motion.feColorMatrix,
  feComposite: motion.feComposite,
  feMerge: motion.feMerge,
  feMergeNode: motion.feMergeNode,
  feOffset: motion.feOffset,
  feFlood: motion.feFlood,
  feBlend: motion.feBlend,
  feImage: motion.feImage,
  feMorphology: motion.feMorphology,
  feTile: motion.feTile,
  feTurbulence: motion.feTurbulence,
  feConvolveMatrix: motion.feConvolveMatrix,
  feDiffuseLighting: motion.feDiffuseLighting,
  feSpecularLighting: motion.feSpecularLighting,
  feDistantLight: motion.feDistantLight,
  fePointLight: motion.fePointLight,
  feSpotLight: motion.feSpotLight,
  feFuncR: motion.feFuncR,
  feFuncG: motion.feFuncG,
  feFuncB: motion.feFuncB,
  feFuncA: motion.feFuncA,
  feComponentTransfer: motion.feComponentTransfer,
  feDisplacementMap: motion.feDisplacementMap,
  feDropShadow: motion.feDropShadow,
}

// Re-export motion for direct usage when needed
export { motion }

// Re-export AnimatePresence for client-side only usage
export { AnimatePresence } from 'framer-motion'
