'use client'

import { ComponentProps, forwardRef } from 'react'

// Simple motion wrapper that renders as regular HTML elements during SSR
// and only applies motion on client-side
const createMotionComponent = (tag: string) => {
  const Component = forwardRef<any, ComponentProps<any>>((props, ref) => {
    const { children, ...rest } = props
    
    // Filter out Framer Motion props that shouldn't be passed to DOM elements
    const {
      initial,
      animate,
      exit,
      transition,
      variants,
      whileHover,
      whileTap,
      whileFocus,
      whileInView,
      whileDrag,
      drag,
      dragConstraints,
      dragElastic,
      dragMomentum,
      dragPropagation,
      dragSnapToOrigin,
      dragTransition,
      dragControls,
      onDrag,
      onDragStart,
      onDragEnd,
      layout,
      layoutId,
      layoutScroll,
      layoutRoot,
      layoutDependency,
      layoutTransition,
      onLayoutAnimationStart,
      onLayoutAnimationComplete,
      onAnimationStart,
      onAnimationComplete,
      onUpdate,
      onHoverStart,
      onHoverEnd,
      onTap,
      onTapStart,
      onTapCancel,
      onFocus,
      onBlur,
      onInView,
      onViewportEnter,
      onViewportLeave,
      onPan,
      onPanStart,
      onPanEnd,
      onPanSessionStart,
      onPanSessionEnd,
      onDirectionLock,
      onMeasureDragConstraints,
      onDragTransition,
      onLayoutMeasure,
      onBeforeLayoutMeasure,
      onLayoutAnimationStart: onLayoutAnimationStartProp,
      onLayoutAnimationComplete: onLayoutAnimationCompleteProp,
      onAnimationStart: onAnimationStartProp,
      onAnimationComplete: onAnimationCompleteProp,
      onUpdate: onUpdateProp,
      onHoverStart: onHoverStartProp,
      onHoverEnd: onHoverEndProp,
      onTap: onTapProp,
      onTapStart: onTapStartProp,
      onTapCancel: onTapCancelProp,
      onFocus: onFocusProp,
      onBlur: onBlurProp,
      onInView: onInViewProp,
      onViewportEnter: onViewportEnterProp,
      onViewportLeave: onViewportLeaveProp,
      onPan: onPanProp,
      onPanStart: onPanStartProp,
      onPanEnd: onPanEndProp,
      onPanSessionStart: onPanSessionStartProp,
      onPanSessionEnd: onPanSessionEndProp,
      onDirectionLock: onDirectionLockProp,
      onMeasureDragConstraints: onMeasureDragConstraintsProp,
      onDragTransition: onDragTransitionProp,
      onLayoutMeasure: onLayoutMeasureProp,
      onBeforeLayoutMeasure: onBeforeLayoutMeasureProp,
      ...domProps
    } = rest as any
    
    const Element = tag as any
    
    return <Element ref={ref} {...domProps}>{children}</Element>
  })
  
  Component.displayName = `Motion${tag.charAt(0).toUpperCase() + tag.slice(1)}`
  return Component
}

// Create motion components that are SSR-safe
export const motion = {
  div: createMotionComponent('div'),
  section: createMotionComponent('section'),
  article: createMotionComponent('article'),
  header: createMotionComponent('header'),
  footer: createMotionComponent('footer'),
  nav: createMotionComponent('nav'),
  main: createMotionComponent('main'),
  aside: createMotionComponent('aside'),
  button: createMotionComponent('button'),
  span: createMotionComponent('span'),
  p: createMotionComponent('p'),
  h1: createMotionComponent('h1'),
  h2: createMotionComponent('h2'),
  h3: createMotionComponent('h3'),
  h4: createMotionComponent('h4'),
  h5: createMotionComponent('h5'),
  h6: createMotionComponent('h6'),
  ul: createMotionComponent('ul'),
  ol: createMotionComponent('ol'),
  li: createMotionComponent('li'),
  a: createMotionComponent('a'),
  img: createMotionComponent('img'),
  form: createMotionComponent('form'),
  input: createMotionComponent('input'),
  textarea: createMotionComponent('textarea'),
  select: createMotionComponent('select'),
  option: createMotionComponent('option'),
  label: createMotionComponent('label'),
  fieldset: createMotionComponent('fieldset'),
  legend: createMotionComponent('legend'),
  table: createMotionComponent('table'),
  thead: createMotionComponent('thead'),
  tbody: createMotionComponent('tbody'),
  tr: createMotionComponent('tr'),
  th: createMotionComponent('th'),
  td: createMotionComponent('td'),
  canvas: createMotionComponent('canvas'),
  svg: createMotionComponent('svg'),
  path: createMotionComponent('path'),
  circle: createMotionComponent('circle'),
  rect: createMotionComponent('rect'),
  line: createMotionComponent('line'),
  polyline: createMotionComponent('polyline'),
  polygon: createMotionComponent('polygon'),
  ellipse: createMotionComponent('ellipse'),
  g: createMotionComponent('g'),
  defs: createMotionComponent('defs'),
  clipPath: createMotionComponent('clipPath'),
  mask: createMotionComponent('mask'),
  pattern: createMotionComponent('pattern'),
  image: createMotionComponent('image'),
  text: createMotionComponent('text'),
  tspan: createMotionComponent('tspan'),
  foreignObject: createMotionComponent('foreignObject'),
  use: createMotionComponent('use'),
  symbol: createMotionComponent('symbol'),
  marker: createMotionComponent('marker'),
  linearGradient: createMotionComponent('linearGradient'),
  radialGradient: createMotionComponent('radialGradient'),
  stop: createMotionComponent('stop'),
  filter: createMotionComponent('filter'),
  feGaussianBlur: createMotionComponent('feGaussianBlur'),
  feColorMatrix: createMotionComponent('feColorMatrix'),
  feComposite: createMotionComponent('feComposite'),
  feMerge: createMotionComponent('feMerge'),
  feMergeNode: createMotionComponent('feMergeNode'),
  feOffset: createMotionComponent('feOffset'),
  feFlood: createMotionComponent('feFlood'),
  feBlend: createMotionComponent('feBlend'),
  feImage: createMotionComponent('feImage'),
  feMorphology: createMotionComponent('feMorphology'),
  feTile: createMotionComponent('feTile'),
  feTurbulence: createMotionComponent('feTurbulence'),
  feConvolveMatrix: createMotionComponent('feConvolveMatrix'),
  feDiffuseLighting: createMotionComponent('feDiffuseLighting'),
  feSpecularLighting: createMotionComponent('feSpecularLighting'),
  feDistantLight: createMotionComponent('feDistantLight'),
  fePointLight: createMotionComponent('fePointLight'),
  feSpotLight: createMotionComponent('feSpotLight'),
  feFuncR: createMotionComponent('feFuncR'),
  feFuncG: createMotionComponent('feFuncG'),
  feFuncB: createMotionComponent('feFuncB'),
  feFuncA: createMotionComponent('feFuncA'),
  feComponentTransfer: createMotionComponent('feComponentTransfer'),
  feDisplacementMap: createMotionComponent('feDisplacementMap'),
  feDropShadow: createMotionComponent('feDropShadow'),
}

// Simple AnimatePresence that just renders children
export const AnimatePresence = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>
}
