import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/dashboard-demo/',
          '/dashboard-enhanced/',
          '/dashboard-simple/',
          '/auth/login',
          '/auth/logout',
          '/me/',
          '/_next/',
          '/_vercel/',
          '/sw.js',
          '/offline.html',
          '/manifest.webmanifest',
          '/build-with-polyfill.js',
          '/polyfill-*.js',
          '/jest.config.js',
          '/playwright.config.ts',
          '/cypress/',
          '/e2e/',
          '/__tests__/',
          '/coverage/',
          '/.env*',
          '/.git/',
          '/.vscode/',
          '/node_modules/',
          '/.next/',
          '/.turbo/',
          '/.cache/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 0,
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Slurp',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 2,
      },
      {
        userAgent: 'DuckDuckBot',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Baiduspider',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 2,
      },
      {
        userAgent: 'YandexBot',
        allow: '/',
        disallow: [
          '/private/',
          '/admin/',
          '/api/',
          '/dashboard/',
          '/auth/login',
          '/auth/logout',
          '/me/',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: [
      'https://shikshanam.com/sitemap.xml',
    ],
    host: 'https://shikshanam.com',
  }
}
